services:
  database:
    restart: no
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'LANG=en_US.utf8'
      - 'PGDATA=/data/postgres'
    volumes:
      - "postgres:/data/postgres"
  keycloak:
    image: 'quay.io/keycloak/keycloak:22.0.1'
    environment:
      - 'KEYCLOAK_ADMIN=admin'
      - 'KEYCLOAK_ADMIN_PASSWORD=admin'
    ports:
      - "8080:8080"
    command:
      - start-dev
    volumes:
      - 'keycloak:/opt/keycloak/data/'

volumes:
  postgres:
  keycloak:
