services:
  mariosy-backend:
    image: mszlachetko-mariosy-backend
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - database-bridge
  database:
    restart: no
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'LANG=en_US.utf8'
      - 'PGDATA=/data/postgres'
    volumes:
      - "postgres:/data/postgres"
    networks:
      - database-bridge

volumes:
  postgres:

networks:
  database-bridge: